# Generated by Django 4.1.4 on 2023-01-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('M', 'Maintenance'), ('C', 'Clean'), ('R', 'Repair'), ('U', 'Upgrade')], default='M', max_length=1),
        ),
    ]
