# Generated by Django 4.1.4 on 2023-01-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_service_service_type_service_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='type',
        ),
    ]
