# Generated by Django 4.1.4 on 2023-01-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_service_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
    ]
