# Generated by Django 4.1.4 on 2023-01-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='main_app.feature'),
        ),
    ]
